- README.md
modifique el archivo README.md
> primer commit y modificando el README.md

- README.md
modifique el archivo README.md
> cambio hecho desde fork hacia origin

- README.md
> Revert 6 testing

- src/app/components/crear-evento/crear-evento.component.html
- src/app/components/crear-evento/crear-evento.component.scss
- src/app/components/crear-evento/crear-evento.component.ts
- src/app/components/crear-mantenimiento/crear-mantenimiento.component.html
- src/app/components/crear-mantenimiento/crear-mantenimiento.component.scss
- src/app/components/crear-mantenimiento/crear-mantenimiento.component.ts
- src/app/components/crear-salida/crear-salida.component.html
- src/app/components/crear-salida/crear-salida.component.scss
- src/app/components/crear-salida/crear-salida.component.ts
- src/app/components/user-edit/user-edit.component.ts
- src/app/inicio/inicio.component.ts
- src/app/services/evento.service.ts
- src/app/services/lugar.service.ts
- src/app/services/mantenimiento.service.ts
- src/app/services/salida.service.ts
- src/app/services/statusorder.service.ts
los formularios ya funcionan, solo faltan mostrar los errores
> formularios de crear solicitudes ya funcionando y con nuevo diseno

- src/app/components/ver-evento/ver-evento.component.html
- src/app/components/ver-evento/ver-evento.component.scss
- src/app/components/ver-evento/ver-evento.component.ts
- src/app/components/ver-mantenimiento/ver-mantenimiento.component.html
- src/app/components/ver-mantenimiento/ver-mantenimiento.component.scss
- src/app/components/ver-mantenimiento/ver-mantenimiento.component.ts
- src/app/components/ver-salida/ver-salida.component.html
- src/app/components/ver-salida/ver-salida.component.scss
- src/app/components/ver-salida/ver-salida.component.ts
- src/app/inicio/inicio.component.scss
al hacer clic en una solicitud la aplicación te llevara a una sección para ver toda la información de una solicitud, esta parte ya esta terminada (por ahora).
> detalle de solicitudes terminada

- src/app/app.component.scss
- src/app/components/actualizar-evento/actualizar-evento.component.html
- src/app/components/actualizar-evento/actualizar-evento.component.scss
- src/app/components/actualizar-evento/actualizar-evento.component.ts
- src/app/components/actualizar-mantenimiento/actualizar-mantenimiento.component.html
- src/app/components/actualizar-mantenimiento/actualizar-mantenimiento.component.scss
- src/app/components/actualizar-mantenimiento/actualizar-mantenimiento.component.ts
- src/app/components/actualizar-salida/actualizar-salida.component.html
- src/app/components/actualizar-salida/actualizar-salida.component.scss
- src/app/components/actualizar-salida/actualizar-salida.component.ts
- src/app/components/crear-mantenimiento/crear-mantenimiento.component.html
- src/app/components/error/error.component.html
- src/app/components/error/error.component.scss
- src/app/components/user-edit/user-edit.component.ts
- src/app/components/ver-evento/ver-evento.component.html
- src/app/components/ver-evento/ver-evento.component.scss
- src/app/components/ver-mantenimiento/ver-mantenimiento.component.html
- src/app/components/ver-mantenimiento/ver-mantenimiento.component.scss
- src/app/components/ver-salida/ver-salida.component.html
- src/app/components/ver-salida/ver-salida.component.scss
- src/app/reutilizables/banner-crear/banner-crear.component.scss
se ha implementado un boton de actualizar solicitud en cada una de las solicitudes  que los redirige a la solicitud de actualizacion y el header ha cambiado de color.
> formulario de editar solicitudes terminado

- src/app/app.routing.ts
- src/app/components/perfil/perfil.component.html
- src/app/components/user-edit/user-edit.component.html
- src/app/components/user-edit/user-edit.component.scss
- src/app/components/user-edit/user-edit.component.ts
- src/app/inicio/inicio.component.scss
- src/app/inicio/inicio.component.ts
- src/app/login/login.component.scss
- src/app/login/login.component.ts
- src/app/services/user.service.ts
pagina de editar usuario ya funciona, pero cambiar el avatar aun no.
> editar usuario funciona pero avatar aun no

- src/app/app.component.html
- src/app/app.component.scss
- src/app/app.component.ts
- src/app/components/user-edit/user-edit.component.html
se ha mejorado la imagen de perfil por defecto, y el menu de usuario se ve bien en todos los navegadores.
> mejorando menu de usuario y foto de perfil

- src/app/components/ver-salida/ver-salida.component.ts
> aplicacion funcionando

- src/app/app.component.scss
- src/app/inicio/inicio.component.scss
- src/app/login/login.component.scss
- src/app/registro/registro.component.html
- src/app/registro/registro.component.scss
correccion de errores en el responsive web design de varias paginas
> responsive web design 3

- src/app/app.component.scss
se trata de corregir un error de margin en el menu hamburguesa en la version para dispositivos moviles
> correcicones en menu hamburguesa

- src/app/app.component.scss
solucionando desbordamiento de menu hamburguesa
> solucionando errores de webkit

- src/app/app.component.scss
- src/app/components/crear-evento/crear-evento.component.scss
- src/app/components/crear-mantenimiento/crear-mantenimiento.component.scss
- src/app/components/crear-salida/crear-salida.component.scss
- src/app/components/eventos/eventos.component.scss
- src/app/components/mantenimiento/mantenimiento.component.scss
- src/app/components/perfil/perfil.component.scss
- src/app/components/salidas/salidas.component.scss
> solucionando erroreS

- src/app/adminComponents/actualizar-departamento/actualizar-departamento.component.html
- src/app/adminComponents/actualizar-departamento/actualizar-departamento.component.scss
- src/app/adminComponents/actualizar-departamento/actualizar-departamento.component.ts
- src/app/adminComponents/crear-departamento/crear-departamento.component.html
- src/app/adminComponents/crear-departamento/crear-departamento.component.scss
- src/app/adminComponents/crear-departamento/crear-departamento.component.ts
- src/app/adminComponents/crear-transporte/crear-transporte.component.ts
- src/app/adminComponents/departamentos/departamentos.component.html
- src/app/adminComponents/departamentos/departamentos.component.scss
- src/app/adminComponents/departamentos/departamentos.component.ts
- src/app/adminComponents/ver-departamento/ver-departamento.component.html
- src/app/adminComponents/ver-departamento/ver-departamento.component.scss
- src/app/adminComponents/ver-departamento/ver-departamento.component.ts
- src/app/adminComponents/ver-transporte/ver-transporte.component.ts
- src/app/app.component.html
- src/app/app.routing.ts
- src/app/reutilizables/card-carrousel/card-carrousel.component.html
- src/app/reutilizables/card/card.component.html
- src/app/reutilizables/solicitud-botones/solicitud-botones.component.html
- src/app/reutilizables/solicitud-box/solicitud-box.component.html
Maquetación de la sección de departamentos completada con éxito
> crud de departamentos maquetado con exito

- src/app/services/departamento.service.ts
Solucionado error en los servicios que impedía la creación y edición de nuevos departamentos
> departamentos funcionando

- src/app/adminComponents/clndrio/clndrio.component.html
- src/app/adminComponents/clndrio/clndrio.component.scss
- src/app/adminComponents/clndrio/clndrio.component.spec.ts
- src/app/adminComponents/clndrio/clndrio.component.ts
- src/app/app.module.ts
- src/app/app.routing.ts
- src/app/services/evento.service.ts
- src/app/services/mantenimiento.service.ts
- src/app/services/salida.service.ts
El calendario está terminado, muestra las solicitudes de salidas, mantenimiento y eventos de forma dinámica al usuario.
> clndrio terminado y funcionando

- src/app/app.component.html
El calendario está listo para ser utilizado y en el menú se agregó la dirección para entrar al calendario.
> clndrio terminado y disponible en menu

- src/app/adminComponents/clndrio/clndrio.component.html
- src/app/adminComponents/clndrio/clndrio.component.scss
- src/app/adminComponents/clndrio/clndrio.component.ts
- src/app/app.component.scss
se ha implementado un suavisado en el calendario al scrollear automaticamente
> scroll suavisazo en calendario

- src/app/adminComponents/clndrio/clndrio.component.scss
- src/app/app.component.scss
- src/app/app.module.ts
- src/app/components/eventos/eventos.component.html
- src/app/components/eventos/eventos.component.scss
- src/app/components/mantenimiento/mantenimiento.component.html
- src/app/components/mantenimiento/mantenimiento.component.scss
- src/app/components/salidas/salidas.component.html
- src/app/components/salidas/salidas.component.scss
- src/app/reutilizables/card-grid/card-grid.component.scss
- src/app/reutilizables/stats/stats.component.html
- src/app/reutilizables/stats/stats.component.scss
- src/app/reutilizables/stats/stats.component.spec.ts
- src/app/reutilizables/stats/stats.component.ts
agregando funcionalidades del calendario extras al repositorio
> detalles del calendario

- src/app/adminComponents/clndrio/clndrio.component.html
- src/app/adminComponents/clndrio/clndrio.component.scss
- src/app/adminComponents/clndrio/clndrio.component.ts
- src/app/app.component.html
- src/app/app.component.scss
- src/app/app.component.ts
- src/app/inicio/inicio.component.ts
- src/app/login/login.component.html
- src/app/login/login.component.scss
- src/app/registro/registro.component.scss
- src/app/reutilizables/banner-inicio/banner-inicio.component.html
Se ha implementado una mejora estética en la experiencia de usuario en el uso del calendario, se ha agregado una sección de estadísticas y el menú de navegación se ve mas elegante y estable, además el código se ha reducido y se ha hecho mas limpio.
> terminadas las estadisticas del calendario

- src/app/adminComponents/clndrio/clndrio.component.ts
- src/app/inicio/inicio.component.ts
Se eliminó el código de try catch que se implementó pero no dio resultados.
> eliminacion del try catch

- src/app/app.component.html
- src/app/app.module.ts
- src/app/app.routing.ts
- src/app/components/bitacora/bitacora.component.html
- src/app/components/bitacora/bitacora.component.scss
- src/app/components/bitacora/bitacora.component.spec.ts
- src/app/components/bitacora/bitacora.component.ts
- src/app/components/registro/registro.component.html
- src/app/components/registro/registro.component.scss
- src/app/components/registro/registro.component.spec.ts
- src/app/components/registro/registro.component.ts
- src/app/components/salidas/salidas.component.ts
Se ha integrado una bitácora dinámica para revisar las salidas de vehículos, independiente de las solicitudes de salidas.
> agregado de bitacora de autos

- src/app/components/user-edit/user-edit.component.ts
> solucionado bug en user-edit

- src/app/app.component.html
- src/app/app.component.scss
correcion de cambios en el menu
> cambios de menu

- src/app/adminComponents/ver-departamento/ver-departamento.component.scss
- src/app/adminComponents/ver-departamento/ver-departamento.component.ts
- src/app/adminComponents/ver-transporte/ver-transporte.component.html
- src/app/adminComponents/ver-transporte/ver-transporte.component.scss
- src/app/adminComponents/ver-transporte/ver-transporte.component.ts
- src/app/reutilizables/card/card.component.html
- src/app/reutilizables/card/card.component.scss
- src/app/reutilizables/card/card.component.ts
- src/app/reutilizables/solicitud-botones/solicitud-botones.component.html
> correccion de errores
